---
- name: Append successful EOS command output
  ansible.builtin.set_fact:
    eos_all_commands: "{{ eos_all_commands | default([]) + cmds }}"
    eos_all_stdout: "{{ eos_all_stdout | default([]) + outs }}"
  when:
    - result is defined
    - not (result.failed | default(false) | bool)
    - (result.stdout | default([]) | length) > 0
  vars:
    cmds: "{{ result.invocation.module_args.commands | default(result.item.commands | default([]), true) }}"
    outs: "{{ result.stdout | default([]) }}"
