---
all:
  children:
    switches:
      children:
        cisco:
          hosts:
            sw-cisco-01:
              ansible_host: 192.0.2.10
              ansible_network_os: cisco.ios.ios
            sw-nxos-01:
              ansible_host: 192.0.2.11
              ansible_network_os: cisco.nxos.nxos
        arista:
          hosts:
            sw-arista-01:
              ansible_host: 192.0.2.20
              ansible_network_os: arista.eos.eos
            pe-oma-01:
              ansible_host: 192.0.2.21
              ansible_network_os: arista.eos.eos
              vrfs:
                - v0000001a
    aggpe:
      hosts:
        pe-oma-01:
    firewalls:
      children:
        paloalto:
          hosts:
            fw-palo-01:
              ansible_host: 192.0.2.30
              palo_vsys: 909-chi-tyson
              palo_is_panorama: false
