---
- name: Rebuild report from existing artifacts
  hosts: all
  gather_facts: false
  run_once: true
  connection: local
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ansible_become: false
  tasks:
    - name: Analyze artifacts
      ansible.builtin.include_tasks: tasks/analyze.yml
